const ASL_IMAGES: { [key: string]: string } = {
  A: "/src/assets/asl-images/a.jpg",
  B: "/src/assets/asl-images/b.jpg",
  C: "/src/assets/asl-images/c.jpg",
  D: "/src/assets/asl-images/d.jpg",
  E: "/src/assets/asl-images/e.jpg",
  F: "/src/assets/asl-images/f.jpg",
  G: "/src/assets/asl-images/g.jpg",
  H: "/src/assets/asl-images/h.jpg",
  I: "/src/assets/asl-images/i.jpg",
  J: "/src/assets/asl-images/j.jpg",
  K: "/src/assets/asl-images/k.jpg",
  L: "/src/assets/asl-images/l.jpg",
  M: "/src/assets/asl-images/m.jpg",
  N: "/src/assets/asl-images/n.jpg",
  O: "/src/assets/asl-images/o.jpg",
  P: "/src/assets/asl-images/p.jpg",
  Q: "/src/assets/asl-images/q.jpg",
  R: "/src/assets/asl-images/r.jpg",
  S: "/src/assets/asl-images/s.jpg",
  T: "/src/assets/asl-images/t.jpg",
  U: "/src/assets/asl-images/u.jpg",
  V: "/src/assets/asl-images/v.jpg",
  W: "/src/assets/asl-images/w.jpg",
  X: "/src/assets/asl-images/x.jpg",
  Y: "/src/assets/asl-images/y.jpg",
  Z: "/src/assets/asl-images/z.jpg",
};

export default ASL_IMAGES;
